### ISSUE TITLE
CentOS 7.5 - Cockpit 178 RHEL Subscription Manager dependency reintroduced

### ISSUE THREAD

**Issue by PeterFalken** [cockpit-project/cockpit#10132]
It reintroduces the RHEL subscription and few other packages (Kernel Dump, SELinux, Diagnostic Reports, Subscriptions) that aren't needed by default in a default CentOS system.

**Comment by martinpitt** [comment]
This was fixed for good in commit 567b68e7, which is a much more robust way to prevent this problem in the future. Current COPR builds now stopped building cockpit-networkmanager and similar packages which are bundled in cockpit-system on RHEL/CentOS:

https://copr-be.cloud.fedoraproject.org/results/@cockpit/cockpit-preview/epel-7-x86_64/00802849-cockpit/

**Comment by PeterFalken** [comment]
Thanks Martin.

**Comment by PeterFalken** [comment]
Martin - I just checked the dependencies for the newly released Cockpit 179 on CentOS 7.5
It still show as having the subscription-manager from RedHat as a dependency. So the cocktail-packagekit does't seem to be installed.

<img width="851" alt="screen shot 2018-10-05 at 4 50 40 pm" src="https://user-images.githubusercontent.com/2557898/46563575-7ad6b400-c8bf-11e8-8f4a-897ef5a823d5.png">

**Comment by martinpitt** [comment]
@PeterFalken : Argh, sorry. I'll send a PR.
