### ISSUE TITLE
SSH Private Key not adding

### ISSUE THREAD

**Issue by alexhorner** [cockpit-project/cockpit#12432]
Cockpit version: 164
OS: Ubuntu Minimal 18.04 LTS
Page: Authentication

Steps to reproduce

1. Sign in
2. Go to Account menu, top right, click Authentication
3. Add private key
4. Point to valid key (with or without password)
5. Enter password if required
6. Press Add, nothing happens, goes back to empty key list

**Comment by KKoukiou** [comment]
@alexhorner it would be useful if you could paste any errors/warnings you see in the js console.

**Comment by alexhorner** [comment]
```
Enter passphrase for /location/mykey.rsa: 

Bad passphrase, try again for /location/mykey.rsa: 
```
The bad passphrase happens before I've even entered the passphrase, but after I have entered the passphrase and clicked `Add`:
```
cat: '*.pub': No such file or directory
```

Additionally, every few seconds I get
```
failed to list keys in home directory: cat: '*.pub': No such file or directory
cat: '*.pub': No such file or directory
```

however I think this is because I have no keys in my user's home directory under .ssh?

**Comment by jmullentech** [comment]
Sadly, my repeated Google searches have landed me here. I have the same problem on a CentOS 8 install, connecting with two other machines added to Cockpit. 

_Exactly_ as reported by @alexhorner , I can add the key and it immediately reverts to the empty display. Oddly, after uploading the keys, I can then click either of the other two servers and both are auth'd via the keys immediately... but if I log out of Cockpit and re-log, I have to upload both keys again or it fails to auth and prompts for a password. Something is screwy. Three browsers, three machines, same result.

I have no idea how to see the "js console". Any input on how to further diagnose what is happening here?

**Comment by alexhorner** [comment]
@jmullentech You can open the Developers Panel and along the top of it click Console by doing CTRL+SHIFT+i on both Firefox and Chrome.

The fix you described does not work for me

**Comment by jmullentech** [comment]
I know this is above my pay-grade but what happens to the error messages in the js console once you add the *.pub files to your `~/.ssh` directory? 

In my case, I moved my two public keys to that directory (on the primary Cockpit server) and the errors immediately stopped spamming the console. Then, once I went back to the Authentication menu and added my keys, everything worked as intended.

**Comment by alexhorner** [comment]
IIRC these error messages in the console remained no matter what I attempted to do

**Comment by helamonster** [comment]
I am experiencing this problem on version 214.1 on Ubuntu 20.04

Upon opening the authentication dialog, the web console shows (and continues to show about once per second: 
> 3dashboard.js:5
```
failed to list keys in home directory: cat: '*.pub': No such file or directory
```

The SSH private key I am attempting to add is located:
`/home/user/.ssh/user+ed25519@domain.tld`

Once I add the path to a valid key (but before clicking 'Add'):
> index.js:72 
```
Enter passphrase for /home/user/.ssh/user+ed25519@domain.tld: 
Bad passphrase, try again for /home/user/.ssh/user+ed25519@domain.tld: 
```

As soon as I click the Add button (or, interestingly, as soon as the password field looses focus):
> onloadwff.js:71
```
Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLInputElement.blurListener
```
After investigating further, I found that the `onloadwff.js` file is from the LastPass Chrome extension, so it seems there is a conflict there. But even after disabling that extension entirely, all I see after clicking "add" is:
> cockpit.js:606
```
cat: '*.pub': No such file or directory

p @ cockpit.js:606
m @ cockpit.js:616
v @ cockpit.js:511
a.onmessage.o.dispatch_data @ cockpit.js:441
index.js:72 failed to list keys in home directory: cat: '*.pub': No such file or directory
```

I'm not sure why its checking for the pub key files which home directory it is referring to, but putting the public key file in every home directory on the cockpit server had no effect.

**Comment by Tuumke** [comment]
+1
I don't know how to read error logs? But i have the same problem. The key does seem to work, sort of.
Have 3 hosts, 1 host (ubuntu 18.04) with dockers and a reverse proxy for cockpit. then we add 2 hosts (s01.server.com and s02.server.com). Both ubuntu 18.04, same pvt keys for ssh, same use, same password. I can enter s02 each time but for s01 i first have to add the pvt key again.

**Comment by pgnd** [comment]
same issue with new installs
```
rpm -qa | grep cockpit-2
	cockpit-227-1.fc32.x86_64
```

on
```
grep PRETTY /etc/os-release
	PRETTY_NAME="Fedora 32 (Server Edition)"
```

attempting to add any known-valid ssh key from own-path, e.g.
```
/sec/ssh/ssh.desk0153.2020-05-09.ed25519
```
unable to nav to path & select; unable to enter path-to-key.

rather than fussing around with this UI, where can privkeys be added manually to config?

are there docs for such manual add?

@jmullentech re:

> EDIT: Ok, for anyone that stumbles into this. After you do your ssh-keygen magic and get your keys, you have to add the resulting *.pub files to the primary Cockpit server's ~/.ssh directory. This should definitely be made clear in the docs. By doing so, now everything is working exactly as described/intended.

can you clarify specifically what you've done/added?  it's not clear what files into which '~/.ssh' you're referring to.

**Comment by Filz0r** [comment]
> same issue with new installs
> 
> ```
> rpm -qa | grep cockpit-2
> 	cockpit-227-1.fc32.x86_64
> ```
> 
> on
> 
> ```
> grep PRETTY /etc/os-release
> 	PRETTY_NAME="Fedora 32 (Server Edition)"
> ```
> 
> attempting to add any known-valid ssh key from own-path, e.g.
> 
> ```
> /sec/ssh/ssh.desk0153.2020-05-09.ed25519
> ```
> 
> unable to nav to path & select; unable to enter path-to-key.
> 
> rather than fussing around with this UI, where can privkeys be added manually to config?
> 
> are there docs for such manual add?
> 
> @jmullentech re:
> 
> > EDIT: Ok, for anyone that stumbles into this. After you do your ssh-keygen magic and get your keys, you have to add the resulting *.pub files to the primary Cockpit server's ~/.ssh directory. This should definitely be made clear in the docs. By doing so, now everything is working exactly as described/intended.
> 
> can you clarify specifically what you've done/added? it's not clear what files into which '~/.ssh' you're referring to.

He meant that on the primary machine you want to be able to access all the other servers besides adding the private key to the .ssh folder on the user in the primary machine you must also add the public key to that folder for example:
- you create a priv/pub key pair named example and example.pub on your local machine
-Then you send both files to the .ssh folder over on the main server users account
after that all is working as expected, but as he stated this is not present in the documentation

**Comment by jmullentech** [comment]
@FilzOr Yep, that's exactly what I meant! Apologies for long delay here, 2020 has been a ride. But that's precisely what I had done. Thanks for clarifying for him.

**Comment by KKoukiou** [comment]
Can some of the people involded in this issue maybe verify that the problem is solved with 256. We rewrote that dialog with:
```
Author: Katerina Koukiou <kkoukiou@redhat.com>
Date:   Mon Oct 11 16:45:23 2021 +0200

    shell: rewrite credentials dialog to React and Patternfly 4
```

**Comment by marusak** [comment]
I believe that this talks about the same things as does #16585
That issue has been fixed with https://github.com/cockpit-project/cockpit/commit/1251e7c21847be64e489469de15efc5b44083089 which was released in version 261

If you update to this version and the issue persists, please reopen

**Comment by mike-def** [comment]
Hey there, I recently found the Cockpit as a great tool for what I need, but I immediately run into this issue - so it seems it is still not fixed.
I use Kubuntu 22.10, Cockpit 277-1 and the issue is exactly the same as described above (I pick a valid private SSH key, then I click on Add button, and it disappears without any changes). JS console shows only repeated "failed to list keys in home directory: cat: '*.pub': No such file or directory" error, nothing more.
Is there anything else what I can try/do?

**Comment by dancojocaru2000** [comment]
This issue is still not fixed. If a public key is not in the same directory as the private key, the private key cannot be added.

**Comment by mike-def** [comment]
In my case, I have the public and the private key in the same directory and I can't add it anyway...

**Comment by CodingWithAnxiety** [comment]
Updates on this issue? I am still getting this on Rocky Linux.

**Comment by IIPoliII** [comment]
same issue here

**Comment by thering1975TG** [comment]
Same as here in OCt 2023, latest backport version as of today on Debian 12 - was only testing but seeing how old this issue is and the fact it still has no solution leads me to find a more stable and responsive solution

**Comment by Filz0r** [comment]
A possible solution for this issue could be forcing the user to also upload his public key when the private key is uploaded.

As per a previous comment I posted here, an easy solution for this issue is to just copy both key files onto the .ssh folder of the user of the server running cockpit, as long as your permissions are properly set and you have both key files in the .ssh folder everything should work well

**Comment by TheSainEyereg** [comment]
Same issue

**Comment by kaxing** [comment]
Check the browser console: `failed to list keys in home directory: cat: '*.pub': No such file or directory.`
I had to move *.pub files into `~/.ssh/` to make this work.

The silence from the web interface after adding a private key from another path seems to be causing this confusion.
