### ISSUE TITLE
cockpit-protocol-WARNING **: couldn't read from connection: Peer failed to perform TLS handshake

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#1348]
Hi,
there are message n console, when manual running cockpit-ws. They are caused by self-signed certificate and probably should be supressed, because it is expected to have bad handshake in case of selfsigned certificate.
Steps to reproduce:
cd cockpit
mkdir build2
cd build2/
../autogen.sh --prefix=/opt/cockpit2 --enable-maintainer-mode --enable-debug --enable-prefix-only
make
make install
systemctl stop cockpit.socket
systemctl stop cockpit.service
/opt/cockpit2/sbin/remotectl certificate --ensure --user=root --group=
/opt/cockpit2/libexec/cockpit-ws&
sleep 5

curl https://192.168.122.168:9090
-> (cockpit-ws:18730): cockpit-protocol-WARNING **: couldn't read from connection: Peer failed to perform TLS handshake

curl https://192.168.122.168:9090 --insecure
works without error appeared in running cockpit instance

**Comment by SteveMB1** [comment]
Chrome won't work with an IP address. Try a resolvable URL.
curl -I --insecure https://127.0.0.1:9090.
This should solve the issue.

**Comment by martinpitt** [comment]
This bug report is over 4 years old and never got investigated. Since then, pretty much everything in Cockpit changed. If you have similar troubles today, can you please file a new issue? Thanks!

**Comment by danst0** [comment]
The bug still seems to exist. I just installed cockpit on a Ubuntu 18.04 server. I tried to connect to ip-addres:9090.
Same error message

**Comment by tripLr** [comment]
Same issue 
2019

**Comment by schweidj** [comment]
Same error here. With actual Safari and Firefox on IOS 13.

**Comment by marinovdh** [comment]
Same issue here on Debian 9 with Google Chrome to connect to. It worked yesterday, so something on my side has changed. But what...? I hope I can figure it out.

**Comment by chris1984** [comment]
Still an issue on Chrome and Edge

**Comment by felipeomegaelev** [comment]
Ainda aqui 2022 Edge

**Comment by fsdrw08** [comment]
Still an issue on Chrome and Edge, 2023
