### ISSUE TITLE
Problem installing and running cockpit on Debian Bullseye

### ISSUE THREAD

**Issue by DavidFW1960** [cockpit-project/cockpit#16232]
Cockpit version: latest trying to install
OS: Debian Bullseye

Issue description
When I follow instructions I get an error:
```
david@debian-bullseye:~$ sudo apt install -t bullseye-backports cockpit
Reading package lists... Done
E: The value 'bullseye-backports' is invalid for APT::Default-Release as such a release is not available in the sources
david@debian-bullseye:~$
```
Please help us out by explaining how to reproduce it.
I have followed the direction to add backports file in sources and it has:
deb http://deb.debian.org/debian bullseye-backports main
as the source. If I change bullseye to buster it does install and I can open the web page but when I login I get an error
Connection failed
There was an unexpected error while connecting to the machine.
Messages related to the failure might be found in the journal:
journalctl -u cockpit
```
etc etc
My cockpit.conf:
```
[WebService]
Origins = https://domain.com:xxxxx http://10.90.11.100:19090
ProtocolHeader = X-Forwarded-Proto
```
(Running through a reverse proxy but the local IP also does the same error.
My listen.conf
```
[Socket]
ListenStream=
ListenStream=19090
```
This was working fine on Buster BTW....



Relevant parts of the system log are also useful:
`journalctl --since -10m` if the issue happened in the last 10 minutes
`journalctl -u cockpit -u <unit>` if you know which unit it concerns
```

Aug 12 08:24:32 debian cockpit-ws[18556]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Aug 12 08:26:01 debian systemd[1]: cockpit.service: Succeeded.
Aug 13 09:08:49 debian systemd[1]: Starting Cockpit Web Service...
Aug 13 09:08:49 debian systemd[1]: Started Cockpit Web Service.
Aug 13 09:08:49 debian cockpit-ws[26903]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Aug 13 09:10:19 debian systemd[1]: cockpit.service: Succeeded.
Aug 13 09:22:00 debian systemd[1]: Starting Cockpit Web Service...
Aug 13 09:22:00 debian systemd[1]: Started Cockpit Web Service.
Aug 13 09:22:00 debian cockpit-ws[28048]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Aug 13 09:23:30 debian systemd[1]: cockpit.service: Succeeded.
Aug 15 10:09:37 debian systemd[1]: Starting Cockpit Web Service...
Aug 15 10:09:37 debian systemd[1]: Started Cockpit Web Service.
lines 1-39

Steps to reproduce

1. Try to install
2. Try to run
3.

In case the issue is clearly visible, screenshots are very helpful

When I use IP Address
![image](https://user-images.githubusercontent.com/36390762/129503711-ec31e7a6-35e8-4c80-98c1-af089b434491.png)
When I go via domain
![image](https://user-images.githubusercontent.com/36390762/129503765-74a2270a-2c1c-4f51-84eb-d3bd4664f5cd.png)

**Comment by DavidFW1960** [comment]
I edited the bloody template because I kept losing half of the text I entered.....

**Comment by garrett** [comment]
I get the same results as @DavidFW1960 when adding the Bullseye backport:

```
E: The value 'bullseye-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```

I have Cockpit running on my Raspberry Pi 1, which is set up as a pihole DNS server. It is on Debian Bullseye. The Bullseye version is old, as expected, as it's Cockpit 239 instead of 250.

![Screenshot 2021-08-18 at 11-23-07 Overview - garrett pihole](https://user-images.githubusercontent.com/10246/129873293-b53411de-7009-43a0-a803-2cf6973c33b6.png)
![Screenshot 2021-08-18 at 11-05-33 Services - garrett pihole](https://user-images.githubusercontent.com/10246/129873322-4ea2ab32-6e57-4756-a947-63b2d09751be.png)

And I ran the instructions as mentioned on Cockpit-Project.org, just as @DavidFW1960 has done.

```
$ sudo sh
# echo 'deb http://deb.debian.org/debian bullseye-backports main' > \
 /etc/apt/sources.list.d/backports.list> 
# apt update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Get:2 http://deb.debian.org/debian bullseye-backports InRelease [37.0 kB]
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Fetched 37.0 kB in 12s (3072 B/s)                                                                       
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
# sudo apt install -t bullseye-backports cockpit
Reading package lists... Done
E: The value 'bullseye-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```

As this is a Pi 1 running Debian, the architecture is `armel`. I guess backports doesn't have a builds yet?

**Comment by martinpitt** [comment]
That was indeed a [know problem](https://lists.debian.org/debian-backports/2021/08/msg00008.html_) a few weeks ago right after Debian 11 was released, as the backports repo did not exist yet.  It does now, so the instructions work now. I also backported Cockpit 251 to bullseye the other day.

**Comment by DavidFW1960** [comment]
![image](https://user-images.githubusercontent.com/36390762/131289142-70b6ccc2-a60a-4343-af92-e9d02732adf1.png)
Still not loading

**Comment by martinpitt** [comment]
@DavidFW1960 : Please check `dpkg -l | grep cockpit` that you really have the latest versions of everything. Most probably you just updated the empty metapackage "cockpit" but are missing "cockpit-system"?

**Comment by DavidFW1960** [comment]
```
ii  cockpit                              251-1~bpo10+1                  all          Web Console for Linux servers
ii  cockpit-bridge                       251-1~bpo10+1                  amd64        Cockpit bridge server-side component
ii  cockpit-machines                     239-1                          all          Cockpit user interface for virtual machines
ii  cockpit-networkmanager               251-1~bpo10+1                  all          Cockpit user interface for networking
ii  cockpit-packagekit                   251-1~bpo10+1                  all          Cockpit user interface for packages
ii  cockpit-storaged                     251-1~bpo10+1                  all          Cockpit user interface for storage
ii  cockpit-system                       251-1~bpo10+1                  all          Cockpit admin interface for a system
ii  cockpit-ws                           251-1~bpo10+1                  amd64        Cockpit Web Service
```
That is what I have with that command

**Comment by martinpitt** [comment]
OK, so your cockpit packages are up to date now. You are still getting the "cockpit not found" error in the console now (as you edited your latest comment, and the screenshot is now gone)? Can you try `sudo systemctl stop cockpit` to make sure it runs the latest version?

**Comment by DavidFW1960** [comment]
```
david@debian:~$ sudo systemctl stop cockpit
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
david@debian:~$ sudo systemctl daemon-reload
david@debian:~$ sudo journalctl -u cockpit.socket
-- Journal begins at Sun 2021-08-22 13:30:43 AEST, ends at Mon 2021-08-30 16:21:55 AEST. --
Aug 27 11:22:48 debian systemd[1]: Stopping Cockpit Web Service Socket.
Aug 27 11:22:48 debian systemd[1]: cockpit.socket: Succeeded.
Aug 27 11:22:48 debian systemd[1]: Closed Cockpit Web Service Socket.
-- Boot f2cb8f6cb1af4e6f9e118407e8cbfaf7 --
Aug 27 11:27:10 debian systemd[1]: Starting Cockpit Web Service Socket.
Aug 27 11:27:10 debian systemd[1]: Listening on Cockpit Web Service Socket.
Aug 30 15:12:24 debian systemd[1]: Stopping Cockpit Web Service Socket.
Aug 30 15:12:24 debian systemd[1]: cockpit.socket: Succeeded.
Aug 30 15:12:24 debian systemd[1]: Closed Cockpit Web Service Socket.
Aug 30 15:12:24 debian systemd[1]: Starting Cockpit Web Service Socket.
Aug 30 15:12:24 debian systemd[1]: Listening on Cockpit Web Service Socket.
Aug 30 15:20:14 debian systemd[1]: Stopping Cockpit Web Service Socket.
Aug 30 15:20:14 debian systemd[1]: cockpit.socket: Succeeded.
Aug 30 15:20:14 debian systemd[1]: Closed Cockpit Web Service Socket.
Aug 30 15:20:14 debian systemd[1]: Starting Cockpit Web Service Socket.
Aug 30 15:20:14 debian systemd[1]: Listening on Cockpit Web Service Socket.
Aug 30 15:25:04 debian systemd[1]: Stopping Cockpit Web Service Socket.
Aug 30 15:25:04 debian systemd[1]: cockpit.socket: Succeeded.
Aug 30 15:25:04 debian systemd[1]: Closed Cockpit Web Service Socket.
Aug 30 15:25:04 debian systemd[1]: Starting Cockpit Web Service Socket.
Aug 30 15:25:04 debian systemd[1]: Listening on Cockpit Web Service Socket.
david@debian:~$ 
```

**Comment by DavidFW1960** [comment]
Why did you close this? It still doesn't work???? @martinpitt

**Comment by martinpitt** [comment]
I closed it because the original problem ("The value 'bullseye-backports' is invalid for APT::Default-Release") was fixed on the Debian side more than a month ago. There is no information here what doesn't work right now, can you please describe the details? Thanks!

**Comment by DavidFW1960** [comment]
I still get the connection failed error as shown in the screenshot in the original post

**Comment by martinpitt** [comment]
@DavidFW1960 : As there is no useful previous context here, let's start from the beginning. So apparently your `systemctl status cockpit` is fine, and `systemctl status cockpit.socket` should be running? What does `curl http://localhost:9090` say?

**Comment by DavidFW1960** [comment]
As per the above I changed the port to 19090 as something else was using 9090
 ```
curl http://localhost:19090
<!DOCTYPE html>
<html>

<head>
  <title>Loading...</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex">
  <meta insert_dynamic_content_here><base href="/">
    <script>
var environment = {"page":{"connect":true,"require_host":false},"hostname":"debian","os-release":{"NAME":"Debian GNU/Linux","ID":"debian","PRETTY_NAME":"Debian GNU/Linux 11 (bullseye)"}};
    </script>
  <script type="text/javascript">
    /* Patch IE to support forEach on NodeLists, used in show/hide */
    if (window.NodeList && !NodeList.prototype.forEach)
        NodeList.prototype.forEach = Array.prototype.forEach;
  </script>
  <script type="text/javascript">/*insert_translations_here*/</script>
  <script type="text/javascript" src="cockpit/static/login.js"></script>
  <link href="cockpit/static/login.css" type="text/css" rel="stylesheet">
  <link href="cockpit/static/branding.css" type="text/css" rel="stylesheet">
</head>

<body class="login-pf">
  <div id="banner" class="pf-c-alert pf-m-info pf-m-inline dialog-error" aria-label="inline danger alert" hidden>
    <svg fill="currentColor" viewBox="0 0 448 512" aria-hidden="true">
      <path d="M224 512c35.32 0 63.97-28.65 63.97-64H160.03c0 35.35 28.65 64 63.97 64zm215.39-149.71c-19.32-20.76-55.47-51.99-55.47-154.29 0-77.7-54.48-139.9-127.94-155.16V32c0-17.67-14.32-32-31.98-32s-31.98 14.33-31.98 32v20.84C118.56 68.1 64.08 130.3 64.08 208c0 102.3-36.15 133.53-55.47 154.29-6 6.45-8.66 14.16-8.61 21.71.11 16.4 12.98 32 32.1 32h383.8c19.12 0 32-15.6 32.1-32 .05-7.55-2.61-15.27-8.61-21.71z" />
    </svg>
    <span id="banner-message" class="pf-c-alert__title"></span>
  </div>

  <span id="badge"></span>

  <div class="container">
    <h1 id="brand" class="hide-before"></h1>

    <div id="error-group" class="pf-c-alert pf-m-danger pf-m-inline dialog-error noscript" aria-label="inline danger alert">
      <svg fill="currentColor" viewBox="0 0 512 512" aria-hidden="true">
        <path d="M504 256c0 136.997-111.043 248-248 248S8 392.997 8 256C8 119.083 119.043 8 256 8s248 111.083 248 248zm-248 50c-25.405 0-46 20.595-46 46s20.595 46 46 46 46-20.595 46-46-20.595-46-46-46zm-43.673-165.346l7.418 136c.347 6.364 5.609 11.346 11.982 11.346h28.546c6.373 0 11.635-4.982 11.982-11.346l7.418-136c.375-6.874-5.098-12.654-11.982-12.654h-63.383c-6.884 0-12.356 5.78-11.981 12.654z" />
      </svg>
      <h2 id="login-error-message" class="pf-c-alert__title">
        <span class="noscript" translate>Please enable JavaScript to use the Web Console.</span>
      </h2>
    </div>

    <div id="info-group" class="pf-c-alert pf-m-info pf-m-inline dialog-error" aria-label="inline danger alert" hidden>
      <svg fill="currentColor" viewBox="0 0 512 512" aria-hidden="true">
        <path d="M256 8C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm0 110c23.196 0 42 18.804 42 42s-18.804 42-42 42-42-18.804-42-42 18.804-42 42-42zm56 254c0 6.627-5.373 12-12 12h-88c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h12v-64h-12c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h64c6.627 0 12 5.373 12 12v100h12c6.627 0 12 5.373 12 12v24z" />
      </svg>
      <h2 id="login-info-message" class="pf-c-alert__title"></h2>
    </div>

    <div id="login" class="login-area" hidden>
      <form onsubmit="return false">

        <div id="conversation-group" class="form-group" hidden>
          <div id="conversation-message"></div>
          <label id="conversation-prompt" for="conversation-input"></label>
          <input type="password" class="form-control" id="conversation-input">
        </div>

        <div id="hostkey-group" class="form-group" hidden>
          <h1 id="hostkey-title"></h1>
          <div id="hostkey-warning-group" class="pf-c-alert pf-m-warning pf-m-inline dialog-error" aria-label="inline warning alert" hidden>
            <svg fill="currentColor" viewBox="0 0 576 512" aria-hidden="true"><path d="M569.52 440.01c18.46 32-4.71 71.99-41.58 71.99H48.05c-36.93 0-60-40.05-41.57-71.99L246.42 24c18.47-32.01 64.72-31.96 83.16 0L569.52 440zM288 354a46 46 0 100 92 46 46 0 000-92zm-43.67-165.35l7.41 136A12 12 0 00263.74 336h48.54a12 12 0 0011.98-11.35l7.42-136A12 12 0 00319.7 176h-63.38a12 12 0 00-11.98 12.65z"/></svg>
            <h2 translate class="pf-c-alert__title">Changed keys are often the result of an operating system reinstallation. However, an unexpected change may indicate a third-party attempt to intercept your connection.</h2>
              </div>
          <p id="hostkey-message-1"></p>
          <p translate>To ensure that your connection is not intercepted by a malicious third-party, please verify the host key fingerprint:</p>
          <pre id="hostkey-fingerprint"></pre>
          <p id="hostkey-type"></p>
          <p id="hostkey-verify-help-1"></p>
          <pre id="hostkey-verify-help-cmds"></pre>
          <p translate>The resulting fingerprint is fine to share via public methods, including email.</p>
          <p translate>If the fingerprint matches, click "Accept key and log in". Otherwise, do not log in and contact your administrator.</p>
        </div>

        <div id="user-group" class="form-group">
          <label for="login-user-input" class="control-label" translate>User name</label>
          <input type="text" class="form-control" id="login-user-input" autocorrect="off" autocapitalize="none" autofocus>
        </div>

        <div id="password-group" class="form-group">
          <label for="login-password-input" class="control-label" translate>Password</label>
          <input type="password" class="form-control" id="login-password-input">
        </div>

        <div id="option-group">
          <a href="#" id="show-other-login-options">
            <svg height="16" width="16" viewBox="0 0 16 16" id="option-caret" class="caret caret-right" aria-hidden="true">
              <polygon fill="#ffffff" points="4,0 4,14 12,7"></polygon>
            </svg><span id="show-other-login-options-text" translate>Other options</span>
            <!-- Above: Span needs to be immediately next to SVG to prevent whitespace in the link -->
          </a>
        </div>

        <div id="server-group" class="form-group" hidden>
          <label title="Log in to another system. Leave blank to log in to the local system." for="server-field" class="control-label" translate>Connect to</label>
          <div class="server-box">
            <input type="text" class="form-control" id="server-field">
            <span class="cross" id="server-clear" aria-hidden="true">&#x274c;</span>
          </div>
        </div>

        <div class="form-group login-actions">
          <button class="pc-c-button pf-m-primary login-button" id="login-button" type="submit">
            <span class="spinner"></span>
            <span id="login-button-text" translate>Log in</span>
          </button>
          <a id="get-out-link" href="/" translate>Cancel</a>
        </div>
      </form>
    </div>

    <div id="login-wait-validating" hidden>
      <span class="help-block" translate>Validating authentication token</span>
      <span class="spinner col-xs-15"></span>
    </div>

    <div id="login-fatal" hidden>
      <div id="login-fatal-message"></div>
      <a id="login-again" translate hidden>Try again</a>
    </div>

    <div class="unsupported-browser" id="unsupported-browser" hidden>
      <h2 class="unsupported-browser-heading" translate>A modern browser is required for security, reliability, and performance.</h2>
      <div class="browser-recommendations">
        <div class="browser-download">
          <h3 translate>Download a new browser for free</h3>
          <ul>
            <li><a href="https://firefox.com/">Mozilla Firefox</a> / Linux, Windows, macOS</li>
            <li><a href="https://www.google.com/chrome/">Google Chrome</a> / Linux, Windows, macOS</li>
          </ul>
        </div>
        <div class="browser-bundled">
          <h3 translate>Or use a bundled browser</h3>
          <ul>
            <li><a href="https://www.microsoft.com/">Microsoft Edge</a> / Windows</li>
            <li><a href="https://www.apple.com/safari/">Apple Safari</a> / macOS</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="details" id="login-details" hidden>
    <p>
      <label class="control-label"><span translate>Server</span>: <b id="server-name"></b></label>
    </p>
    <p id="login-note" class="login-note"></p>
  </div>

  <script type="text/javascript">
    /* Hide everything classed as "noscript" */
    document.querySelectorAll('.noscript').forEach(function(element){
      element.hidden = true;
    });
  </script>
</body>
</html>
david@debian:~$
```

**Comment by DavidFW1960** [comment]
```

david@debian:~$ systemctl status cockpit
● cockpit.service - Cockpit Web Service
     Loaded: loaded (/lib/systemd/system/cockpit.service; static)
     Active: inactive (dead) since Sat 2021-11-06 14:27:08 AEDT; 43s ago
TriggeredBy: ● cockpit.socket
       Docs: man:cockpit-ws(8)
    Process: 294714 ExecStartPre=/usr/lib/cockpit/cockpit-certificate-ensure (code=exited, status=0/SUCCESS)
    Process: 294715 ExecStart=/usr/lib/cockpit/cockpit-tls (code=exited, status=0/SUCCESS)
   Main PID: 294715 (code=exited, status=0/SUCCESS)
        CPU: 306ms
david@debian:~$
```
```
david@debian:~$ systemctl status cockpit.socket
● cockpit.socket - Cockpit Web Service Socket
     Loaded: loaded (/lib/systemd/system/cockpit.socket; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/cockpit.socket.d
             └─listen.conf
     Active: active (listening) since Thu 2021-11-04 08:59:05 AEDT; 2 days ago
   Triggers: ● cockpit.service
       Docs: man:cockpit-ws(8)
     Listen: [::]:19090 (Stream)
      Tasks: 0 (limit: 9004)
     Memory: 1.0M
        CPU: 21ms
     CGroup: /system.slice/cockpit.socket

Warning: some journal files were not opened due to insufficient permissions.
```

**Comment by DavidFW1960** [comment]
My listen.conf and cockpit.conf files
```
sudo nano /etc/systemd/system/cockpit.socket.d/listen.conf

[Socket]
ListenStream=
ListenStream=19090

sudo nano /etc/cockpit/cockpit.conf

[WebService]
Origins = https://mydomain:port http://10.90.11.100:19090
ProtocolHeader = X-Forwarded-Proto
```

**Comment by martinpitt** [comment]
> If I go to the URL

That would be what then? https://mydomain:port ? That's a reverse proxy? The wiki has recipes for [nginx](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX) and [apache](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt)

Do you get some error message in the browser's JavaScript console? (Ctrl+Shift+J)

> Origins = https://mydomain:port http://10.90.11.100:19090

Can you try to add wss://mydomain:port ?

**Comment by DavidFW1960** [comment]
> > If I go to the URL
> 
> That would be what then? https://mydomain:port ? That's a reverse proxy? The wiki has recipes for [nginx](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX) and [apache](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt)
> 
> Do you get some error message in the browser's JavaScript console? (Ctrl+Shift+J)
> 
> > Origins = https://mydomain:port http://10.90.11.100:19090
> 
> Can you try to add wss://mydomain:port ?

the url is http://10.90.11.100:19090 I said that below the screenshot (actually I said localhost but it was the local ip address)
When I was on Buster it was working perfectly with this exact configuration via the reverse_proxy (Caddy in my case)

I will try adding wss://mydomain:port but I did play with the listen.conf to delete the extra Listenstream= and then I couldn't restart cockpit so I might need to reboot the system. When I try and restart it I see this:
```

david@debian:~$ sudo systemctl restart cockpit.socket
Job failed. See "journalctl -xe" for details.
david@debian:~$ journalctl -xe
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
░░
░░ The job identifier is 15.
Nov 07 14:09:20 debian systemd[418415]: Reached target Sockets.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit UNIT has finished successfully.
░░
░░ The job identifier is 7.
Nov 07 14:09:20 debian systemd[418415]: Reached target Basic System.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit UNIT has finished successfully.
░░
░░ The job identifier is 6.
Nov 07 14:09:20 debian systemd[418415]: Reached target Main User Target.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit UNIT has finished successfully.
░░
░░ The job identifier is 5.
Nov 07 14:09:20 debian systemd[418415]: Startup finished in 447ms.
░░ Subject: User manager start-up is now complete
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The user manager instance for user 1000 has been started. All services queued
░░ for starting have been started. Note that other services might still be starting
░░ up or be started at any later time.
░░
░░ Startup of the manager took 447928 microseconds.
Nov 07 14:09:26 debian sudo[418504]:    david : TTY=pts/0 ; PWD=/home/david ; USER=root ; COMMAND=/usr/bin/systemctl restart cockpi>
Nov 07 14:09:26 debian sudo[418504]: pam_unix(sudo:session): session opened for user root(uid=0) by david(uid=1000)
Nov 07 14:09:26 debian sudo[418504]: pam_unix(sudo:session): session closed for user root
```

So you want me to change /etc/cockpit/cockpit.conf
```
[WebService]
Origins = https://mydomain:port http://10.90.11.100:19090 wss://mydomain:port
ProtocolHeader = X-Forwarded-Proto
```

**Comment by DavidFW1960** [comment]
So now cockpit wants to use 19090 and 9090???
```
Error response from daemon: driver failed programming external connectivity on endpoint sabnzbd (9d0c324326d9ce5e0bef61268caf11b735138fd42d33da75a7235ff2c04c6261): Error starting userland proxy: listen tcp4 0.0.0.0:9090: bind: address already in use
david@debian:~$ sudo ss -tulpen | grep 9090
tcp   LISTEN 0      4096                                              *:19090            *:*    users:(("systemd",pid=1,fd=109)) ino:1375096 sk:6c cgroup:/system.slice/cockpit.socket v6only:0 <->                                                                     
tcp   LISTEN 0      4096                                              *:9090             *:*    users:(("systemd",pid=1,fd=77)) ino:1375281 sk:7a cgroup:/system.slice/cockpit.socket v6only:0 <->                                                                      
```

**Comment by martinpitt** [comment]
Did you `systemctl daemon-reload` and `systemctl restart cockpit.socket` after creating /etc/systemd/system/cockpit.socket.d/listen.conf? Please check `systemctl cat cockpit.socket` that it actually picked up the change. (The file content looks good). The above journalctl would have shown it, but you ran it as user, not root (through sudo).

**Comment by DavidFW1960** [comment]
OK!! So debian updates today for this and it's finally working again!
