### ISSUE TITLE
cockpit allows root log in using his password even when sshd is configured to not permit root login

### ISSUE THREAD

**Issue by bachradsusi** [cockpit-project/cockpit#1790]
It means that when admin disallow user root login via sshd, it's still possible via cockpit where as far as I know is terminal emulator which makes it effectivelly same as login via ssh.

So it would be great if cockpit could somehow share PermitRootLogin configuration with sshd. 

The global configuration of sshd could be dumped using '/usr/sbin/sshd -T'. However, sshd_conf support Match blocks and options like PermitRootLogin can set to different values for different Match option.  A configuration for particular host, port, user or so could be dumped   using '/usr/sbin/sshd -T -C "user=root" -C "host=localhost" ...'

Steff's suggestion is to use a pam module called like pam_check_sshd_config which would use above commands to check if root login is permitted or not. 

Likewise, Cockpit could  respect other sshd authentication settings as  AllowUsers, PasswordAuthentication and others

**Comment by stefwalter** [comment]
Hmmm, I wonder if we should have a big 'respect ssh login settings' knob to control this. In many distros it would be on by default. I wonder where such a knob would live. Needs a bit more thought.

Are you interested in helping implement such a PAM module? It could be incubated in our sources. We already have raw C code and PAM module in src/reauthorize.

**Comment by stefwalter** [comment]
Workaround: In ```/etc/pam.d/cockpit``` have this as the first line:
```
auth requisite pam_succeed_if.so uid >= 1000
```

**Comment by martinpitt** [comment]
You can of course disallow root logins in /etc/pam.d/cockpit, just as one can disallow it for ssh, gdm, or VTs. It seems wrong to me to somehow "look at" ssh's PAM config, as it's a separate thing and may not even apply to cockpit.

The other option is to always use ssh to log into localhost as well, like the bastion host mode does, i. e. start cockpit-ws with `--local-ssh` (but that's not something we test or document). It's probably best to conceptually treat cockpit as parallel to gdm, ssh, or VT logins (which it really is).

**Comment by jtagcat** [comment]
The knob should be added to `/users#/root`. It would be nice, if the toggle could be added to every user - you can disable users other than root from logging in to cockpit.

**Comment by matteo-pennisi** [comment]
If you want to let just the root to be able to access cockpit add this line at the beginning of `/etc/pam.d/cockpit`
```
auth       requisite    pam_succeed_if.so uid eq 1000
```

**Comment by Oaklight** [comment]
You can also edit the `/etc/pam.d/cockpit` to include this following line:
```
# List of users to deny access to Cockpit, by default root is included.
auth       required     pam_listfile.so item=user sense=deny file=/etc/cockpit/disallowed-users onerr>
```
and add a file `/etc/cockpit/disallowed-users` with `root` listed in it

**Comment by martinpitt** [comment]
For the record, this was fixed a year ago in https://cockpit-project.org/blog/cockpit-280.html -- for new installations, root isn't allowed to login by default.

**Comment by Oaklight** [comment]
Yes @martinpitt, I'm aware of the new cockpit behavior. Just some people may still have some very old hardware only able to run debian 10 or other old distribution. My post is about how to patch it up manually :D
