### ISSUE TITLE
Timer side note isn't dark themed

### ISSUE THREAD

**Issue by LunarTwilight** [cockpit-project/cockpit#18948]
### Explain what happens

1. Open a timer systemd unit
2. Timer side note is hard to read
![image](https://github.com/cockpit-project/cockpit/assets/13520392/e4dcf0f7-0da7-4055-b88d-876ceeccb20a)

### Version of Cockpit

287-1~bpo11+1

### Where is the problem in Cockpit?

Services

### Server operating system

Debian

### Server operating system version

11

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
This was fixed in 8161b4da26b which is available Cockpit 290.

**Comment by LunarTwilight** [comment]
> This was fixed in [8161b4d](https://github.com/cockpit-project/cockpit/commit/8161b4da26b92c2fcdbac7bb85b78a2af53a1921) which is available Cockpit 290.

That commit doesn't fix the issue I mentioned, also my repo doesn't have 290 for some reason (`cockpit is already the newest version (287-1~bpo11+1).`), but I assume that's something debian needs to take care of, not y'all?

**Comment by martinpitt** [comment]
Not yet.. Debian just released and unfroze. I now need to wait until 294.1 propagates to Debian testing, see https://tracker.debian.org/pkg/cockpit . In the best case that happens in 3 days, then I can backport it.
