### ISSUE TITLE
CentOS 148 Machines base.css 404

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#7665]
Cockpit 148 has just been pushed to CentOS Extras - I was eager to try out the new vnc console. Unfortunately it's not working - there appear to be two issues in the debugger:

1) vnc.html is calling /include/base.css , which is returning a 404 status. The exact url being called is:
```
https://192.168.1.2:9095/cockpit/$88a775dd106623518e3209f0e483fd36b8c3a828/machines/include/base.css
```
2) vnc.js is throwing the following exception:

```
Msg: Must set host and port
i.Error @ vnc.js:sourcemap:211
````

**Comment by stefwalter** [comment]
I happened to notice that #7139 includes a fix for this.

**Comment by mareklibra** [comment]
Right, this is fixed in Cockpit 153.

**Comment by dcrdev** [comment]
Whilst the missing base stylesheet is no longer an issue, still seeing "Msg: Must set host and port" . This is on 156, still CentOS 7.4.

**Comment by mareklibra** [comment]
@dcrdev , how was the virtual machine created?

Secondly, can you please attach result of following?

    virsh -r dumpxml [VM_NAME]

**Comment by dcrdev** [comment]
@mareklibra vm was created using virt-manager over ssh on a Fedora 26 client; display is set to vnc.

Here is the virsh output you wanted:
```<domain type='kvm' id='2'>
  <name>win10</name>
  <uuid>2a946a99-7b6f-47dc-a10f-dc71d08ac074</uuid>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-rhel7.0.0'>hvm</type>
    <boot dev='cdrom'/>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
    </hyperv>
  </features>
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>Skylake-Client</model>
    <feature policy='require' name='hypervisor'/>
    <feature policy='disable' name='arat'/>
  </cpu>
  <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>destroy</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/win10.qcow2'/>
      <backingStore/>
      <target dev='hda' bus='ide'/>
      <alias name='ide0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/var/lib/libvirt/images/en-gb_windows_10_enterprise_version_1511_x64_dvd_7224923.iso'/>
      <backingStore/>
      <target dev='hdb' bus='ide'/>
      <readonly/>
      <alias name='ide0-0-1'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <controller type='usb' index='0' model='ich9-ehci1'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x7'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci1'>
      <alias name='usb'/>
      <master startport='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0' multifunction='on'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci2'>
      <alias name='usb'/>
      <master startport='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci3'>
      <alias name='usb'/>
      <master startport='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'>
      <alias name='pci.0'/>
    </controller>
    <controller type='ide' index='0'>
      <alias name='ide'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <interface type='network'>
      <mac address='52:54:00:0a:3a:2e'/>
      <source network='default' bridge='virbr0'/>
      <target dev='vnet0'/>
      <model type='rtl8139'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <source path='/dev/pts/2'/>
      <target port='0'/>
      <alias name='serial0'/>
    </serial>
    <console type='pty' tty='/dev/pts/2'>
      <source path='/dev/pts/2'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <input type='tablet' bus='usb'>
      <alias name='input0'/>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'>
      <alias name='input1'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input2'/>
    </input>
    <graphics type='vnc' port='5900' autoport='yes' listen='127.0.0.1'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
    <video>
      <model type='vga' vram='16384' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='dynamic' model='selinux' relabel='yes'>
    <label>system_u:system_r:svirt_t:s0:c235,c358</label>
    <imagelabel>system_u:object_r:svirt_image_t:s0:c235,c358</imagelabel>
  </seclabel>
  <seclabel type='dynamic' model='dac' relabel='yes'>
    <label>+107:+107</label>
    <imagelabel>+107:+107</imagelabel>
  </seclabel>
</domain>```

**Comment by dcrdev** [comment]
Any debugging steps that I could take?

**Comment by dcrdev** [comment]
Worth noting  that I'm running cockpit itself on a non-standard port - maybe that makes a difference? I'll try it on the default port when I get  a chance.

**Comment by mareklibra** [comment]
Please
- try stop firewall (`iptables -L` to be empty), it might be interfering 
- send output of `rpm -qa|grep cockpit`

**Comment by dcrdev** [comment]
Aha...

So not a firewall issue, but a proxy one.

I'm using an Apache reverse proxy for cockpit and it appears that's causing it to not work. Direct access works fine.

Are there any headers that I can send - to make it recognise that I'm running it on port https://cockpit.mydomain.com:443 ?

```
<VirtualHost *:80>
    ServerName cockpit.domain.com
    Redirect permanent / https://cockpit.domain.com/
</VirtualHost>

<VirtualHost *:443>
    ServerName cockpit.domain.com
    ErrorLog /storage/WWW/cockpit.domain.com/error.log
    CustomLog /storage/WWW/cockpit.domain.com/requests.log combined

    ForceType text/html 
    AllowEncodedSlashes On
    
    SSLProxyEngine On
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    
    RequestHeader set Front-End-Https "On"
    ProxyPreserveHost On
    ProxyRequests off

    ProxyPass / https://127.0.0.1:9095/
    ProxyPassReverse / https://127.0.0.1:9095/

    # Main websocket
    ProxyPass "/cockpit/socket" "wss://127.0.0.1:9095/cockpit/socket"

    # Dynamically Upgrade Websocket
    RewriteEngine on
    RewriteCond %{REQUEST_URI} ^/cockpit/socket [NC,OR]
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
    RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
    RewriteRule .* wss://127.0.0.1:9095%{REQUEST_URI} [P,QSA,L]
    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
    RewriteRule .* https://127.0.0.1:9095%{REQUEST_URI} [P,QSA,L]

    # Set Proxy Intention Headers
    RequestHeader set Origin "https://127.0.0.1:9095"
    RequestHeader set X-Forwarded-Proto "https"

    SSLEngine on
    SSLCertificateFile      /etc/httpd/ssl/server.pem
    SSLCertificateChainFile /etc/pki/CA/cacert.pem
    SSLCertificateKeyFile   /etc/httpd/ssl/server.key

    SSLProtocol             all -SSLv2 -SSLv3 -TLSv1
    SSLCipherSuite          ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA3$
    SSLHonorCipherOrder     on

    # HSTS (mod_headers is required) (15768000 seconds = 6 months)
    Header always set Strict-Transport-Security "max-age=15768000"
</VirtualHost>
```

**Comment by petervo** [comment]
@mareklibra are we making a direct connection with a new websocket? Or are we using a cockpit channel as a mock websocket?

**Comment by dcrdev** [comment]
So I've been doing some digging and when cockpit is bare and not behind the proxy - it's making several new connections:

- A new websocket connection at /cockpit/socket - so in total there's 2 of these.
- A websocket connection at /cockpit/channel/<some-guid>

Behind the proxy I'm getting the additional connection at /cockpit/socket, but not the one at /cockpit/channel ; I'm not catering for cockpit/channel in my proxy config yet, but the connection is not even being tried and failing at the moment.

**Comment by mareklibra** [comment]
@petervo , there's channel used. The noVnc's RFB is connecting to
`host:port/cockpit/channel/[TOKEN]?[QUERY]`
where `QUERY` is JSON for binary stream of particular VM's noVNC host:port

**Comment by mareklibra** [comment]
@dcrdev , is /cockpit/channel endpoint handled in your proxy configuration?

**Comment by dcrdev** [comment]
It's not currently, no because I was not aware of the /cockpit/channel endpoint.

That being said - what actually initiates that websocket? Surely I should see failed requests to host:port/cockpit/channel/[TOKEN]?[QUERY] ? I'm not seeing anything....

**Comment by mareklibra** [comment]
Not even within the browser (watch for Network after F12 in Chrome or FF)?

The `host` and `port` are taken from browser's window URL, most probably 192.168.1.2:9095 , considering the initial issue description. Does it meet your setup?

Can you please copy&paste browser's full console log?

**Comment by dcrdev** [comment]
No that's my point -

In the debugger - not via proxy:
- Host / Origin Request Header is 192.168.1.2:9095
- Successful websocket connection being established on /cockpit/channel/[TOKEN]?[QUERY]

In the debugger - via proxy:
- Host / Origin Request Header is just cockpit.domain.com - port is getting stripped because it's 443.
- There are no connection attempts (failed or otherwise) to /cockpit/channel/[TOKEN]?[QUERY]

Console output is simply:
```Msg: Must set host and port```

**Comment by mareklibra** [comment]
Found it. It's a bug. Thanks, I'll post a fix.

**Comment by mareklibra** [comment]
@dcrdev , done. Please let me now if it helps.

**Comment by mareklibra** [comment]
Fix added to https://github.com/cockpit-project/cockpit/pull/8234 to avoid merge conflicts
